"""Schemas for Phase 3 consequence learning."""

from dataclasses import dataclass
from core.cognitive.reflexion.schemas import HealthCategory

# Default threshold for determining if a lesson should become an InsightZettel
DEFAULT_ZETTEL_SIGNIFICANCE_THRESHOLD = 0.6


@dataclass
class OutcomeAssessment:
    """Result of assessing an autonomous decision's outcome.

    Compares health states before and after the observation window
    to determine if the decision succeeded or failed.
    """

    success: bool
    health_before: HealthCategory
    health_after: HealthCategory


@dataclass
class Lesson:
    """Extracted lesson from a decision outcome.

    Generated by curator with significance scoring to determine
    whether this lesson should become an InsightZettel.
    """

    text: str
    significance: float  # 0.0-1.0

    def should_create_zettel(self, threshold: float = DEFAULT_ZETTEL_SIGNIFICANCE_THRESHOLD) -> bool:
        """Check if this lesson is significant enough for a zettel.

        Args:
            threshold: Minimum significance score (default 0.6)

        Returns:
            True if significance >= threshold
        """
        return self.significance >= threshold
